---
- hosts: all
  become: yes

  tasks:
    - name: installing multiple software
      yum: name='{{item}}' state=installed
      with_items:
        - httpd
        - mysql
        - docker
        - java
        - tree

